### ISSUE TITLE
Release 0.0.3?

### ISSUE THREAD

**Issue by FreedomBen** [blackfist/iptools#7]
I forked the project to fix a couple of build warnings in the latest release on Hex (0.0.2), but it looks like they've already been fixed!  The `mix.exs` file has version 0.0.3 in it but that isn't available on Hex.

Can we push a new release?  If this is either abandonware or low priority I'm happy to help out.

**Comment by kf0jvt** [comment]
Thanks for the push - I hadn't realized that I hadn't published the newer release. I push the `0.0.3` release just now and I think I did it right. I'll happily accept help, though, if something isn't right and it's generating errors for people
